# Generated by Django 2.2 on 2020-10-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0002_auto_20201006_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
