# Generated by Django 2.2 on 2020-10-10 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0004_auto_20201008_2333'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
